name: 'Repo Build Number'
description: 'Increments and returns the build number for a repository using `BUILD_NUMBER` repository variable to store the build number.'
author: 'Max Rozdobudko'
branding:
  color: purple
  icon: hash
inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  debug:
    description: Whether to tell the GitHub client to log details of its requests. true or false. Default is to run in debug mode when the GitHub Actions step debug logging is turned on.
    default: ${{ runner.debug == '1' }}
outputs:
  build-number:
    description: 'The build number for the repository'
runs:
  using: 'node20'
  main: 'dist/index.js'
